### ISSUE TITLE
MacOS64: TRSA.LoadOpenSSL fails with "[RSA] Unable to get proc address for "PEM_read_bio_RSA_PUBKEY"

### ISSUE THREAD

**Issue by SchneiderInfosystems** [paolo-rossi/delphi-jose-jwt#26] opened 2019-08-02 15:57 UTC
I tried out today the new MacOS 64 bit compiler, which is delivered with De 10.3.2.

Under Mojave version 10.14.5 I ran into an exception in TRSA.LoadOpenSSL '[RSA] Unable to get proc address for' PEM_read_bio_RSA_PUBKEY ''.

In the Mac32 target platform, the same code is still running properly as before. I also get the same version information from the OpenSSL Cryptolib on MacOS64 as on MacOS32 (query with _SSLeay_Version (SSLEAY_VERSION)): "LibreSSL 2.2.7".

Note: For MACOS you do not need to include the OpenSSL dynlib files into the project deployment because they are already part of the OSX.

Thank you for any tip to solve this issue.

**Comment by paolo-rossi** [comment] 2019-11-16 16:07
Hi Christoph,

sorry for the veery long time it took me! :-)

Have you resolved the issue? 

Paolo.

**Comment by SchneiderInfosystems** [comment] 2019-11-20 07:39
Hi Paolo

No, I didn't find time to analyze this issue. Sorry ;)

Christoph

**Comment by Bbommel** [comment] 2020-11-26 15:53
Hi Paolo,

I'm having the same problem but with Win32/Win64, using Delphi Rio 10.3.3 and libeay32.dll version 1.0.2u.

Compiling and running the application targeting Win32 works just fine (as far as I can see right now). But when I select Win64 as a target, I also get the same error. Within the class procedure TRSA.LoadOpenSSL the line
_PEM_read_bio_RSA_PUBKEY := GetProcAddress(GetCryptLibHandle, 'PEM_read_bio_RSA_PUBKEY');
doesn't set an address for that function, so the exception is raised. 

I running out of ideas whats going wrong here. Just to be sure, I looked into the dll with a tool called "DLL Export Viewer" and of cause the function PEM_read_bio_RSA_PUBKEY exists in this dll. Also, wenn the function "Load" of the unit IdSSL.OpenSSLHeaders is called a few moments before this, it sets _PEM_read_bio_RSAPublicKey successfully (I tried to replace PEM_read_bio_RSA_PUBKEY with PEM_read_bio_RSAPublicKey in your function, but that didn't help).

I'm running out of ideas. What is wrong with this "simple" GetProcAddress?

**Comment by Bbommel** [comment] 2020-11-27 11:09
Got it, and I think that may also be the reason for the same issue with MacOS64.

In the Indy release that is shipped with Delphi 10.3, the function GetCryptLibHandle, that is used in TRSA.LoadOpenSSL, is of the type integer. This is okay for 32-Bit-OS, but on a 64-Bit-OS this may result in an illefal typecast and corrupts the value of the handle to the crypto library (e.g. "libeay32.dll" under Windows).

This is fixed in Indy that is shipped with Delphi 10.4. Using Delphi 10.3.3 or earlier it can manually be fixed by copying the unit IdSSLOpenSSLHeaders into the project folder and then simply change the type of the function GetCryptLibHandle from integer to HMODULE.

**Comment by paolo-rossi** [comment] 2020-11-29 09:15
Good catch @Bbommel !

Now I know why I wasn't able to reproduce the problem: I always use the updated Indy library from GitHub (as stated in the JWT main README) for all Delphi versions.

I think I can close this long standing issue...

Thanks to you all,
Paolo.

**Closed by paolo-rossi** 2020-11-29 09:15 UTC
